# Deprecated! See Brewfile.
# for e in $(brew cask ls); do echo "brew cask install $e"; done
brew cask install adobe-acrobat-reader
brew cask install amethyst
brew cask install android-file-transfer
brew cask install android-sdk
brew cask install arduino
brew cask install atom-beta
brew cask install bettertouchtool
brew cask install boostnote
brew cask install command-tab-plus
brew cask install dash
brew cask install detexify
brew cask install docker
brew cask install dropbox
brew cask install evernote
brew cask install filemon
brew cask install firefox
brew cask install flux
brew cask install fritzing
brew cask install github
brew cask install gitkraken
brew cask install gitnote
brew cask install gitup
brew cask install harmony
brew cask install hex-fiend
brew cask install inkscape
brew cask install intellij-idea-ce
brew cask install iterm2-beta
brew cask install itsycal
brew cask install jabref
brew cask install java
brew cask install kap
brew cask install karabiner-elements
brew cask install keyboard-maestro
brew cask install keycastr
brew cask install libreoffice
brew cask install logitech-options
brew cask install macdown
brew cask install mactex
brew cask install manictime
brew cask install marginnote
brew cask install mark-text
brew cask install marp
brew cask install meld
brew cask install mendeley
brew cask install messenger
brew cask install microsoft-lync
brew cask install mplayerx
brew cask install mqttfx
brew cask install notable
brew cask install oni
brew cask install osxfuse
brew cask install presentation
brew cask install qlcolorcode
brew cask install qlimagesize
brew cask install qlmarkdown
brew cask install qlprettypatch
brew cask install qlstephen
brew cask install qlvideo
brew cask install quicklook-csv
brew cask install quicklook-json
brew cask install recordit
brew cask install screenflick
brew cask install script-debugger
brew cask install shiftit
brew cask install skim
brew cask install skype
brew cask install slack
brew cask install slate
brew cask install smartgit
brew cask install snagit
brew cask install sourcetree
brew cask install spotify
brew cask install spotify-notifications
brew cask install sqlitemanager
brew cask install sqlitestudio
brew cask install sublime-text
brew cask install tad
brew cask install teamviewer
brew cask install toggl
brew cask install typora
brew cask install ultimaker-cura
brew cask install virtualbox
brew cask install visual-studio-code
brew cask install visual-studio-code-insiders
brew cask install vlc
brew cask install webpquicklook
brew cask install whatsapp
brew cask install wireshark
brew cask install xquartz
