# Deprecated! See Brewfile.
# for e in $(brew ls -tr); do echo "brew install $e"; done
brew install xspin
brew install autoconf
brew install gnu-which
brew install ruby-completion
brew install gem-completion
brew install duff
brew install ent
brew install figlet
brew install findutils
brew install gettext
brew install unar
brew install cowsay
brew install libtool
brew install hr
brew install texi2html
brew install makedepend
brew install intltool
brew install graphviz
brew install libffi
brew install m4
brew install android-platform-tools
brew install pkg-config
brew install libksba
brew install ntfs-3g
brew install adns
brew install make
brew install pv
brew install luajit
brew install aspell
brew install opencv3
brew install clasp
brew install hicolor-icon-theme
brew install gd
brew install docbook
brew install docbook-xsl
brew install mobile-shell
brew install dos2unix
brew install exa
brew install htop-osx
brew install screen
brew install apr-util
brew install scons
brew install afl-fuzz
brew install libass
brew install little-cms2
brew install xvid
brew install libmpc
brew install md5sha1sum
brew install sloccount
brew install sshfs
brew install lame
brew install git-imerge
brew install rsync
brew install libtasn1
brew install unibilium
brew install pinentry
brew install jpeg
brew install python3
brew install loc
brew install gnu-time
brew install fortune
brew install gtksourceview
brew install gtk+
brew install gmp
brew install pygtk
brew install libusb
brew install xz
brew install watch
brew install libunistring
brew install brew-cask-completion
brew install clingo
brew install npth
brew install fribidi
brew install wxmac
brew install the_silver_searcher
brew install bench
brew install lua@5.1
brew install lua
brew install automake
brew install elm
brew install gitup
brew install mmv
brew install xsv
brew install fontconfig
brew install libarchive
brew install re2c
brew install gtk-mac-integration
brew install wdiff
brew install libepoxy
brew install legit
brew install ncurses
brew install yasm
brew install libogg
brew install libvorbis
brew install snappy
brew install theora
brew install cairo
brew install icdiff
brew install watchman
brew install gdbm
brew install idris
brew install libgcrypt
brew install ghi
brew install py2cairo
brew install jq
brew install miller
brew install ocaml
brew install pip-completion
brew install tree
brew install cabal-install
brew install fswatch
brew install haskell-stack
brew install scala
brew install thefuck
brew install nettle
brew install mycli
brew install eigen
brew install hyperfine
brew install graphite2
brew install x264
brew install gnu-sed
brew install grep
brew install diffutils
brew install doxygen
brew install gzip
brew install less
brew install mongodb
brew install fasd
brew install moreutils
brew install pango
brew install rlwrap
brew install spidermonkey
brew install webp
brew install xdot
brew install zeromq
brew install libxml2
brew install binutils
brew install mkcert
brew install ghostscript
brew install htop
brew install libvpx
brew install x265
brew install zsh
brew install libde265
brew install git-extras
brew install libtiff
brew install diff-so-fancy
brew install aom
brew install frei0r
brew install libsoxr
brew install opencore-amr
brew install rtmpdump
brew install flac
brew install libsndfile
brew install libsamplerate
brew install rubberband
brew install speex
brew install giflib
brew install libvterm
brew install fd
brew install shared-mime-info
brew install libassuan
brew install tesseract
brew install ninja
brew install macvim
brew install fish
brew install kapacitor
brew install tig
brew install unzip
brew install python@2
brew install gnu-tar
brew install cscope
brew install gdk-pixbuf
brew install libcerf
brew install pcre
brew install mosh
brew install git
brew install libheif
brew install atk
brew install coreutils
brew install nspr
brew install gsettings-desktop-schemas
brew install libyaml
brew install gtm
brew install openssl
brew install jpeg-turbo
brew install freetype
brew install mpfr
brew install python
brew install libgpg-error
brew install libssh2
brew install berkeley-db
brew install ossp-uuid
brew install unixodbc
brew install leptonica
brew install fltk
brew install sdl2
brew install protobuf
brew install ack
brew install fzf
brew install libtermkey
brew install tokei
brew install tccutil
brew install apr
brew install pandoc
brew install gtk+3
brew install pixman
brew install dive
brew install openjpeg
brew install jemalloc
brew install gobject-introspection
brew install unbound
brew install opam
brew install sphinx-doc
brew install libpng
brew install opus
brew install ocamlbuild
brew install emacs
brew install openexr
brew install gawk
brew install pcre2
brew install ripgrep
brew install ilmbase
brew install hub
brew install opencv
brew install c-ares
brew install libmaxminddb
brew install libsmi
brew install libssh
brew install jansson
brew install libev
brew install icu4c
brew install nghttp2
brew install couchdb
brew install pygobject3
brew install boost
brew install lz4
brew install influxdb
brew install meson
brew install ghc
brew install gifsicle
brew install mono
brew install isl
brew install itstool
brew install pdfgrep
brew install git-lfs
brew install py3cairo
brew install readline
brew install libbluray
brew install chronograf
brew install gradle
brew install ffmpeg
brew install sqlite
brew install qt
brew install swig
brew install mercurial
brew install tmux
brew install poppler
brew install proselint
brew install write-good
brew install clog
brew install task
brew install vit
brew install taskell
brew install gtksourceview3
brew install camlp4
brew install pipenv
brew install go
brew install libomp
brew install bash
brew install gist
brew install jrnl
brew install git-absorb
brew install git-fresh
brew install gnu-getopt
brew install git-now
brew install git-plus
brew install git-recent
brew install git-sizer
brew install git-standup
brew install git-test
brew install erlang@19
brew install openblas
brew install libpq
brew install utf8proc
brew install gcc
brew install yarn
brew install cask-repair
brew install oniguruma
brew install pygobject
brew install ant
brew install travis
brew install gdb
brew install colordiff
brew install nss
brew install telegraf
brew install dmd
brew install wireshark
brew install file-formula
brew install llvm
brew install tbb
brew install libmagic
brew install swi-prolog
brew install spin
brew install m-cli
brew install gitfs
brew install libgit2
brew install pstree
brew install fpp
brew install jid
brew install ncdu
brew install bison
brew install wget
brew install libidn2
brew install parallel
brew install libuv
brew install glib
brew install rust
brew install dub
brew install youtube-dl
brew install bat
brew install p11-kit
brew install openssl@1.1
brew install cython
brew install gnuplot
brew install cmake
brew install pgcli
brew install highlight
brew install perl
brew install harfbuzz
brew install numpy
brew install libevent
brew install neovim
brew install imagemagick
brew install gnupg
brew install subversion
brew install git-quick-stats
brew install gnutls
brew install msgpack
brew install z3
brew install vale
brew install erlang
brew install grafana
brew install node
brew install ansifilter
