# Generated with the next line. No longer needed since vscode's Settings Sync
# for e in $(code --list-extensions); do echo "code --install-extension $e"; done
code --install-extension akamud.vscode-theme-onedark
code --install-extension alefragnani.Bookmarks
code --install-extension alefragnani.numbered-bookmarks
code --install-extension alexcvzz.vscode-sqlite
code --install-extension azemoh.one-monokai
code --install-extension ban.spellright
code --install-extension benspaulding.procfile
code --install-extension christian-kohler.npm-intellisense
code --install-extension clptn.code-paredit
code --install-extension codezombiech.gitignore
code --install-extension DanielBerlin.centroid-gcode-language
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension EFanZh.graphviz-preview
code --install-extension efoerster.texlab
code --install-extension eg2.vscode-npm-script
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension freebroccolo.reasonml
code --install-extension geddski.macros
code --install-extension GitHub.vscode-pull-request-github
code --install-extension GrapeCity.gc-excelviewer
code --install-extension hackwaly.ocaml
code --install-extension hackwaly.ocaml-debugger
code --install-extension hoovercj.haskell-linter
code --install-extension hoovercj.vscode-ghc-mod
code --install-extension James-Yu.latex-workshop
code --install-extension JamesBirtles.svelte-vscode
code --install-extension jaredly.reason-vscode
code --install-extension jcanero.hoogle-vscode
code --install-extension justusadam.language-haskell
code --install-extension maelvalais.dune
code --install-extension mamodom.package-json-dependencies-navigation
code --install-extension marlinfirmware.auto-build
code --install-extension mattn.Lisp
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-azuretools.vscode-azureresourcegroups
code --install-extension ms-azuretools.vscode-cosmosdb
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.hexeditor
code --install-extension ms-vscode.Theme-TomorrowKit
code --install-extension ocamllabs.ocaml-platform
code --install-extension patrys.vscode-code-outline
code --install-extension platformio.platformio-ide
code --install-extension Prisma.prisma
code --install-extension RandomFractalsInc.vscode-data-preview
code --install-extension rubbersheep.gi
code --install-extension s3ramsay.vscode-gtm
code --install-extension samverschueren.linter-xo
code --install-extension Shan.code-settings-sync
code --install-extension siegebell.prettify-symbols-mode
code --install-extension siegebell.vscoq
code --install-extension skattyadz.vscode-quick-scope
code --install-extension svelte.svelte-vscode
code --install-extension TabNine.tabnine-vscode
code --install-extension tecosaur.latex-utilities
code --install-extension toba.vsfire
code --install-extension Vans.haskero
code --install-extension vigoo.stylish-haskell
code --install-extension vsciot-vscode.vscode-arduino
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension WakaTime.vscode-wakatime
code --install-extension WallabyJs.quokka-vscode
code --install-extension wwm.better-align
code --install-extension zhuangtongfa.material-theme
